server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
  redis:
    host: 192.168.100.128
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  kafka:
    bootstrap-servers: 192.168.100.128:9092
    producer:
      acks: all
      retries: 3
    consumer:
      group-id: seckill-order-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    admin:
      auto-create: false  # ← 添加这一行，禁用自动创建主题
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
  pattern:
    dateformat: mm:ss.SSS

# 【秒杀优惠券信息多级缓存改造】本地缓存的配置项(刷新时间、过期时间)、Redis缓存的过期时间
hmdp:
  cache:
    voucher-list:
      mode: caffeine
      refresh-after-write: 5s
      expire-after-write: 10m
      redis-ttl: 30m
      # 逻辑过期时间,用于解决缓存击穿问题(Redis Key永不过期,数据携带逻辑过期时间)
      logical-expire-time: 10m
  order:
    timeout-minutes: 15  # 订单超时时间（分钟）

